name: metabolite_database
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - flask
    - flask-wtf
    - flask-sqlalchemy
    - flask-migrate
    - flask-bootstrap
    - flask-moment
    - python-dotenv
    - dateutil
    - python-language-server>=0.19.0
