name: metabolite_database
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - flask
    - flask-wtf
    - flask-sqlalchemy
    - flask-migrate
    - flask-bootstrap
    - flask-moment
    - python-dotenv