name: metabolite_database
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python>=3.6
    - flask
    - flask-wtf
    - flask-sqlalchemy
    - flask-migrate
    - flask-moment
    - python-dotenv
    - python-dateutil
    - pip:
        - bootstrap-flask
