"""Add standard run notes

Revision ID: 0264fdd579f6
Revises: 5a9a93c261a0
Create Date: 2019-01-30 16:49:54.155723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0264fdd579f6'
down_revision = '5a9a93c261a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard_run', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
