"""Remove molecular weight

Revision ID: 235da5be84e1
Revises: e88462d015da
Create Date: 2018-07-03 09:19:43.960576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235da5be84e1'
down_revision = 'e88462d015da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compound', schema=None) as batch_op:
        batch_op.drop_index('ix_compound_molecular_weight')
        batch_op.drop_column('molecular_weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compound', schema=None) as batch_op:
        batch_op.add_column(sa.Column('molecular_weight', sa.FLOAT(), nullable=True))
        batch_op.create_index('ix_compound_molecular_weight', ['molecular_weight'], unique=False)

    # ### end Alembic commands ###
