"""Add compound lists

Revision ID: 5a9a93c261a0
Revises: 235da5be84e1
Create Date: 2018-11-19 16:39:34.883286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9a93c261a0'
down_revision = '235da5be84e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compound_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compound_list')),
    sa.UniqueConstraint('name', name=op.f('uq_compound_list_name'))
    )
    op.create_table('compoundlists',
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('compound_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compound.id'], name=op.f('fk_compoundlists_compound_id_compound')),
    sa.ForeignKeyConstraint(['compound_list_id'], ['compound_list.id'], name=op.f('fk_compoundlists_compound_list_id_compound_list')),
    sa.PrimaryKeyConstraint('compound_id', 'compound_list_id', name=op.f('pk_compoundlists'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compoundlists')
    op.drop_table('compound_list')
    # ### end Alembic commands ###
