"""compound dbxref retentiontime

Revision ID: 7612cbab8bc7
Revises: 
Create Date: 2018-06-18 12:47:51.749360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7612cbab8bc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chromatography_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('compound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('molecular_formula', sa.String(length=128), nullable=True),
    sa.Column('molecular_weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compound_molecular_formula'), 'compound', ['molecular_formula'], unique=False)
    op.create_index(op.f('ix_compound_molecular_weight'), 'compound', ['molecular_weight'], unique=False)
    op.create_index(op.f('ix_compound_name'), 'compound', ['name'], unique=True)
    op.create_table('external_database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('compound_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dbxref',
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('external_database_id', sa.Integer(), nullable=False),
    sa.Column('external_compound_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['compound_id'], ['compound.id'], ),
    sa.ForeignKeyConstraint(['external_database_id'], ['external_database.id'], ),
    sa.PrimaryKeyConstraint('compound_id', 'external_database_id')
    )
    op.create_table('retention_time',
    sa.Column('chromatography_method_id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('retention_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['chromatography_method_id'], ['chromatography_method.id'], ),
    sa.ForeignKeyConstraint(['compound_id'], ['compound.id'], ),
    sa.PrimaryKeyConstraint('chromatography_method_id', 'compound_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retention_time')
    op.drop_table('dbxref')
    op.drop_table('external_database')
    op.drop_index(op.f('ix_compound_name'), table_name='compound')
    op.drop_index(op.f('ix_compound_molecular_weight'), table_name='compound')
    op.drop_index(op.f('ix_compound_molecular_formula'), table_name='compound')
    op.drop_table('compound')
    op.drop_table('chromatography_method')
    # ### end Alembic commands ###
