"""Add compound notes

Revision ID: a15e67cf35fe
Revises: 0264fdd579f6
Create Date: 2019-01-31 12:50:05.199833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15e67cf35fe'
down_revision = '0264fdd579f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compound', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compound', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
