"""add standard run

Revision ID: e88462d015da
Revises: 
Create Date: 2018-06-21 16:54:46.692617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e88462d015da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chromatography_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chromatography_method')),
    sa.UniqueConstraint('name', name=op.f('uq_chromatography_method_name'))
    )
    op.create_table('compound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('molecular_formula', sa.String(length=128), nullable=True),
    sa.Column('molecular_weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compound'))
    )
    with op.batch_alter_table('compound', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compound_molecular_formula'), ['molecular_formula'], unique=False)
        batch_op.create_index(batch_op.f('ix_compound_molecular_weight'), ['molecular_weight'], unique=False)
        batch_op.create_index(batch_op.f('ix_compound_name'), ['name'], unique=True)

    op.create_table('external_database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('compound_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_database')),
    sa.UniqueConstraint('name', name=op.f('uq_external_database_name'))
    )
    op.create_table('dbxref',
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('external_database_id', sa.Integer(), nullable=False),
    sa.Column('external_compound_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['compound_id'], ['compound.id'], name=op.f('fk_dbxref_compound_id_compound')),
    sa.ForeignKeyConstraint(['external_database_id'], ['external_database.id'], name=op.f('fk_dbxref_external_database_id_external_database')),
    sa.PrimaryKeyConstraint('compound_id', 'external_database_id', name=op.f('pk_dbxref'))
    )
    op.create_table('standard_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('operator', sa.String(length=256), nullable=True),
    sa.Column('mzxml_file', sa.String(length=256), nullable=True),
    sa.Column('chromatography_method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chromatography_method_id'], ['chromatography_method.id'], name=op.f('fk_standard_run_chromatography_method_id_chromatography_method')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standard_run'))
    )
    with op.batch_alter_table('standard_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standard_run_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_standard_run_mzxml_file'), ['mzxml_file'], unique=False)
        batch_op.create_index(batch_op.f('ix_standard_run_operator'), ['operator'], unique=False)

    op.create_table('retention_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=True),
    sa.Column('standard_run_id', sa.Integer(), nullable=True),
    sa.Column('retention_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['compound_id'], ['compound.id'], name=op.f('fk_retention_time_compound_id_compound')),
    sa.ForeignKeyConstraint(['standard_run_id'], ['standard_run.id'], name=op.f('fk_retention_time_standard_run_id_standard_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_time'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retention_time')
    with op.batch_alter_table('standard_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standard_run_operator'))
        batch_op.drop_index(batch_op.f('ix_standard_run_mzxml_file'))
        batch_op.drop_index(batch_op.f('ix_standard_run_date'))

    op.drop_table('standard_run')
    op.drop_table('dbxref')
    op.drop_table('external_database')
    with op.batch_alter_table('compound', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compound_name'))
        batch_op.drop_index(batch_op.f('ix_compound_molecular_weight'))
        batch_op.drop_index(batch_op.f('ix_compound_molecular_formula'))

    op.drop_table('compound')
    op.drop_table('chromatography_method')
    # ### end Alembic commands ###
